version: "3.8"
services:
  pub-db:
    container_name: publications-pg
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data/pub/posts
    env_file:
     - postgres.env
    ports:
     - :"5432:5432"
    restart: unless-stopped
    networks:
     - pub-backend
  pub-app:
    container_name: publications
    build: .
    links:
     - "pub-db:database"
    volumes:
     - log-data:./log/
    env_file:
     - app.env
     - jwt.env
    ports:
     - "8080:8080"
    depends_on:
     - pub-pg
    restart: unless-stopped
    networks:
     - pub-backend
volumes:
  pg-data:
  log-data:
networks:
  pub-backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_bind_ipv4: "127.0.0.1"
