version: "3.8"
services:
  postgres:
    container_name: posts-postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data/pub/posts
    env_file:
     - .env
    ports:
     - :"5432:5432"
    restart: unless-stopped
  app:
    container_name: posts
    build: .
    env_file:
     - .env
    ports:
     - "5431:5432"
     - "8080:8080"
    depends_on:
     - postgres
    restart: unless-stopped
volumes:
  pg-data:
